apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-production
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
