# preprod/dummy-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: default
  labels:
    app: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: nginx:latest   # simple nginx container
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app
  namespace: default
  labels:
    app: dummy-app
spec:
  selector:
    app: dummy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
